### ISSUE TITLE
need a .godot folder for the project

### ISSUE THREAD

**Issue by erikgrahn13** [emilfahlgren/FahlgrahnPlay#1]
Jag testade att skapa ett projekt i Godot och då ger den mig en .godot folder i projeketet. Verkar som du missade att att dra med den i din initial commit.

**Comment by emilfahlgren** [comment]
Folk verkar inte ta med den i sina repon, jag provade att klona repot nu och importera projektet i Godot. Det gick bra och '.godot'-mappen skapades automatiskt då istället. Stänger detta :D
